// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gotutor/handlers"
	"gotutor/services"
)

// Injectors from wire.go:

func InitializeHomeHandler(name string) *handlers.HomeHandler {
	menuService := services.NewMenuService(name)
	homeHandler := handlers.NewHomeHandler(menuService)
	return homeHandler
}

func InitializeTestHandler(name string) *handlers.TestHandler {
	testHandler := handlers.NewTestHandler(name)
	return testHandler
}
