// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gotutor/db"
	"gotutor/handlers"
	"gotutor/services"
)

// Injectors from wire.go:

func InitHomeHandler(name string) *handlers.HomeHandler {
	menuService := services.NewMenuService()
	homeHandler := handlers.NewHomeHandler(menuService)
	return homeHandler
}

func InitTestHandler() *handlers.TestHandler {
	gormDB := db.NewDB()
	menuService := services.NewMenuService()
	testHandler := handlers.NewTestHandler(gormDB, menuService)
	return testHandler
}
